source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'JoyOfDataSturctureApp' do
    pod 'SnapKit', '~> 4.0.0'
	pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
end

